---
- name: Apply EC2 instance configurations
  hosts: all
  become: yes
  roles:
    - ec2_user_mgmt

- name: Enforce AWS API policies
  hosts: localhost
  gather_facts: no
  roles:
    - s3_policy_enforcement