name: Ansible Multi-Region CI/CD Pipeline

on:
  workflow_dispatch:

  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main

jobs:
  # Job to orchestrate all configurations across multiple regions
  apply-ansible-roles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws_region: ["us-east-1", "eu-central-1"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.aws_region }}
      
      - name: Set up Ansible and Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install ansible 
      - run: ansible-galaxy collection install community.aws
      - run: pip install boto3 botocore
      
      - name: Calculate Target Host Group Name
        id: set_group
        run: |
          # Replace hyphen with underscore and prepend 'region_'
          GROUP_NAME="region_${{ matrix.aws_region }}"
          CLEAN_GROUP_NAME="${GROUP_NAME//-/_}"
          
          # Set the cleaned variable as a step output for use later
          echo "CLEAN_GROUP_NAME=$CLEAN_GROUP_NAME" >> $GITHUB_OUTPUT
      - name: Run Master Playbook
        run: ansible-playbook -i ansible/inventory/ ansible/playbooks/site.yml --limit '${{ steps.set_group.outputs.CLEAN_GROUP_NAME }}'
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          AWS_REGION: ${{ matrix.aws_region }}
          BACKBLAZE_APPLICATION_KEY_ID: ${{ secrets.BACKBLAZE_APPLICATION_KEY_ID }}
          BACKBLAZE_APPLICATION_KEY: ${{ secrets.BACKBLAZE_APPLICATION_KEY }}
        #continue-on-error: true
  #validate-backup:
    #runs-on: ubuntu-latest
    #needs: apply-ansible-roles
    #steps:
      #- name: Checkout repository
        #uses: actions/checkout@v4

      #- name: Set up SSH agent
        #uses: webfactory/ssh-agent@v0.9.0
        #with:
          #ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      #- name: Set up Ansible and Python
        #uses: actions/setup-python@v5
        #with:
          #python-version: '3.x'

      #- name: Install Ansible and dependencies
        #run: pip install ansible b2sdk

      #- name: Run Backup Validation Playbook
        #run: ansible-playbook -i Ansible/inventory/test_instances.yml Ansible/playbooks/validate_backup.yml --tags ${{ inputs.database }}_restore
        #env:
          #ANSIBLE_CONFIG: Ansible/ansible.cfg
          #BACKBLAZE_APPLICATION_KEY_ID: ${{ secrets.BACKBLAZE_APPLICATION_KEY_ID }}
          #BACKBLAZE_APPLICATION_KEY: ${{ secrets.BACKBLAZE_APPLICATION_KEY }}